import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import QueryProvider from '@/components/providers/query-provider';
import GlobalStoreProvider from '@/components/providers/global-store-provider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <GlobalStoreProvider>{children}</GlobalStoreProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
